/**
 * ─────────────────────────────────────────────────────────────
 *  PORTFOLIO CONTENT — single source of truth
 * ─────────────────────────────────────────────────────────────
 *  Edit this file to update the site; no component changes needed.
 *  • Content is condensed from the resume — no invented claims.
 *  • Fields marked `TODO` are placeholders to replace.
 */
// Background-removed cutout (generated by scripts/make-portrait-cutout.cjs) so the hero colour is free to change.
import portraitUrl from '../assets/sagar-portrait-cutout.webp'
import type { Certification, ExpertiseArea, IconKey, NavItem, Project, Role, TechItem } from './types'

export const profile = {
  name: 'Sagar Das',
  initials: 'SD',
  role: 'Lead Engineer | UiPath Automation Professional',
  intro: 'Building scalable enterprise automation solutions with UiPath, AI, integrations and intelligent automation.',
  indicators: ['5+ Years Experience', 'UiPath', 'RPA & AI Automation', 'Enterprise Integration'],
  /** Floating labels around the portrait. */
  orbit: ['UiPath', 'RPA', 'AI', 'API', 'Automation', 'Agentic AI'],
  portrait: {
    src: portraitUrl,
    width: 1086,
    height: 1146,
    alt: 'Illustrated portrait of Sagar Das, smiling, in a white T-shirt',
  },
}

export const navigation: NavItem[] = [
  { id: 'about', label: 'About' },
  { id: 'my-work', label: 'My Work' },
  { id: 'experience', label: 'Experience' },
  { id: 'contact', label: 'Contact' },
]

export const about = {
  headline: 'I turn business processes into reliable, intelligent automation.',
  lead: 'Five years of hands-on UiPath delivery across Banking, Finance, Hospitality and Automotive — from first requirement to production support.',
  points: [
    { icon: 'workflow', title: 'End-to-end delivery', text: 'Design, build, deploy and support enterprise automation solutions.' },
    { icon: 'layers', title: 'Broad automation scope', text: 'Process Automation, Test Automation, AI-powered automation and integrations.' },
    { icon: 'target', title: 'Business-first thinking', text: 'Translate business requirements into scalable, maintainable automation.' },
    { icon: 'users', title: 'Collaborative', text: 'Work closely with business analysts, technical teams and clients.' },
    { icon: 'award', title: 'Proven in production', text: '95% bot success rate on first deployment — recognised by client and production teams.' },
    { icon: 'globe', title: 'Global delivery', text: 'Onsite in Saudi Arabia and Indonesia, plus remote client management.' },
  ] satisfies { icon: IconKey; title: string; text: string }[],
  /** Programming languages used alongside automation. */
  languages: ['C#', 'VB.NET', 'Java', 'JavaScript', 'Python'],
  /** Other automation / analytics platforms beyond UiPath. */
  otherTools: ['Automation Anywhere', 'Power Automate', 'Alteryx'],
  stack: [
    { name: 'UiPath', icon: 'bot', caption: 'Enterprise automation platform' },
    { name: 'Orchestrator', icon: 'serverCog', caption: 'Deploy, schedule & govern robots' },
    { name: 'REFramework', icon: 'refresh', caption: 'Robust transactional design' },
    { name: 'Coded Apps', icon: 'codeXml', caption: 'Code-first UiPath apps' },
    { name: 'IXP', icon: 'scanText', caption: 'Intelligent data extraction' },
    { name: 'AI / Agentic Automation', icon: 'brain', caption: 'Agents, GenAI & AI Center' },
    { name: 'API Integration', icon: 'cable', caption: 'REST & Integration Services' },
    { name: 'Database', icon: 'database', caption: 'SQL & data handling' },
    { name: 'Excel / PDF Automation', icon: 'fileSheet', caption: 'Document & data automation' },
    { name: 'Test Automation', icon: 'shieldCheck', caption: 'Functional & regression quality' },
  ] satisfies TechItem[],
}

export const experience: Role[] = [
  {
    company: 'HCLTech',
    title: 'Lead Engineer',
    start: 'Sep 2024',
    end: 'Present',
    current: true,
    points: [
      'Lead enterprise UiPath initiatives spanning process automation, testing, applications, integrations and AI-powered automation.',
      'Build scalable solutions with UiPath Studio, Orchestrator, REFramework, Coded Apps and IXP.',
      'Apply AI and agentic capabilities to create intelligent automation.',
      'Own production support — monitoring, exception handling, logging and RCA.',
    ],
    tags: ['UiPath Studio', 'Orchestrator', 'REFramework', 'Coded Apps', 'IXP', 'Agentic AI'],
  },
  {
    company: 'ITC Infotech',
    title: 'Senior RPA Developer',
    start: 'Nov 2021',
    end: 'Sep 2024',
    points: [
      'Delivered UiPath and Automation Anywhere solutions across web, desktop, database, API, PDF and Excel.',
      'Worked the full delivery lifecycle — preparation and design through deployment and post-production support.',
      'Used Action Center, AI Center, Document Understanding, Integration Services and GenAI.',
      'Partnered with customers and technical teams to turn requirements into automation.',
    ],
    tags: ['UiPath', 'Automation Anywhere', 'Document Understanding', 'AI Center', 'Action Center', 'GenAI'],
  },
]

export const expertise: ExpertiseArea[] = [
  { id: 'rpa', title: 'RPA & Automation', icon: 'workflow', summary: 'Designing and running reliable, scalable robots.', items: ['UiPath Studio', 'REFramework', 'Orchestrator', 'Process Automation'] },
  { id: 'intelligent', title: 'Intelligent Automation', icon: 'sparkles', summary: 'Adding AI, documents and agents to automation.', items: ['IXP', 'Document Understanding', 'AI', 'GenAI', 'Agentic Automation'] },
  { id: 'dev', title: 'Development & Integration', icon: 'code', summary: 'Code and connectors that link automation to systems.', items: ['C#', '.NET', 'APIs', 'Databases', 'Enterprise Applications'] },
  { id: 'testing', title: 'Testing', icon: 'flask', summary: 'Quality built into every automation release.', items: ['UiPath Test Automation', 'Functional Testing', 'Regression Testing', 'Integration Testing'] },
  { id: 'apps', title: 'Applications', icon: 'app', summary: 'The apps and file formats automation works across.', items: ['Coded Apps', 'Excel', 'PDF', 'Web Automation', 'Desktop Automation'] },
]

/**
 * Projects — condensed from the resumes. Client names are deliberately omitted; only the
 * industry domain is shown. Measured outcomes appear only where the resume states them.
 * The first PROJECTS_SHOWN entries are featured; the rest appear under "Show all projects".
 */
export const PROJECTS_SHOWN = 4

export const projects: Project[] = [
  {
    id: 'p01',
    index: '01',
    title: 'Enterprise Intelligent Automation & AI-Driven Process Transformation',
    category: 'Enterprise Automation · AI',
    icon: 'layers',
    domain: 'Multi-domain enterprise',
    location: 'Bengaluru, India',
    role: 'Lead Engineer',
    duration: '2 years',
    description: 'A broad enterprise programme combining UiPath process and test automation with agents, Coded Apps and IXP — supported end to end in production.',
    highlights: [
      'Enterprise UiPath Process Automation',
      'Test Automation',
      'Production Support',
      'Orchestrator',
      'Autonomous & Conversational Agents',
      'Coded Apps',
      'IXP',
      'API and enterprise integrations',
    ],
    tags: ['UiPath', 'Orchestrator', 'Agents', 'Coded Apps', 'IXP', 'APIs'],
    details: {
      challenge: 'Scale automation across enterprise processes while adding AI-driven judgement and keeping production stable.',
      approach: 'Reusable REFramework automations governed in Orchestrator, extended with agents, Coded Apps and IXP, and integrated through APIs.',
      flow: ['Request', 'Agent / App', 'Orchestrator', 'Robot', 'API / Data', 'Monitoring'],
    },
  },
  {
    id: 'p02',
    index: '02',
    title: 'High-Volume Banking Automation Programme',
    category: 'Banking RPA · Advanced REFramework',
    icon: 'serverCog',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    teamSize: '20+',
    description: 'Designed and delivered multiple bots for a banking client, re-architecting the bot model for high-volume processing.',
    highlights: [
      'Advanced REFramework — Dispatcher & Performer in one framework',
      'Scaled capacity from 1,000 to 100,000 transactions per day',
      'Sanity, SIT and UAT testing',
      'Onsite requirements, installation and production movement',
    ],
    tags: ['UiPath', 'REFramework', 'Orchestrator', 'Queues', 'Web & Desktop'],
    outcome: { value: 100, suffix: '×', label: 'capacity — 1,000 → 100,000 transactions/day' },
    details: {
      challenge: 'Banking workloads needed to run at a far higher daily volume than the original bot model allowed.',
      approach: 'Redesigned the bots on Advanced REFramework, combining Dispatcher and Performer into one framework and scaling processing through queues.',
      flow: ['Intake', 'Dispatcher', 'Queue', 'Performers', 'Validation', 'Reporting'],
    },
  },
  {
    id: 'p03',
    index: '03',
    title: 'Enterprise RPA Production Support',
    category: 'Production Support · L2 / L3',
    icon: 'shieldCheck',
    domain: 'Telecommunications',
    location: 'Onsite · Indonesia',
    role: 'Production Support & Developer',
    teamSize: '50',
    description: 'L2/L3 support and enhancement for a large estate of UiPath automations, keeping bots available and within SLA.',
    highlights: [
      'Monitored attended & unattended bots in Orchestrator',
      'Root-cause analysis and preventive fixes',
      'Incidents, problems and changes in ServiceNow',
      'Bot recovery, job restarts and exception management',
      'Runbooks, knowledge articles, SDD and PDD updates',
    ],
    tags: ['UiPath', 'Orchestrator', 'SAP', 'ServiceNow', 'RCA'],
    details: {
      challenge: 'Scheduled monitoring jobs and business-critical bots needed high availability and fast recovery under strict SLAs.',
      approach: 'Proactive monitoring, structured RCA and ITSM-driven incident handling, plus onsite support for infrastructure, installation and production moves.',
      flow: ['Monitor', 'Detect', 'Triage', 'RCA', 'Fix', 'Recover'],
    },
  },
  {
    id: 'p04',
    index: '04',
    title: 'SAP Finance Automation & Platform Migration',
    category: 'SAP Automation · Migration',
    icon: 'database',
    domain: 'Manufacturing',
    location: 'Offshore · India',
    role: 'UiPath Developer',
    teamSize: '6',
    description: 'Migrated an existing Blue Prism process to UiPath and automated SAP/Excel finance use cases, removing Excel-macro dependencies.',
    highlights: [
      'Blue Prism → UiPath migration',
      'Variance Analysis Report generation',
      'Internal Order processing',
      'Exception handling and Orchestrator runs',
    ],
    tags: ['UiPath', 'SAP', 'Excel', 'Orchestrator', 'Migration'],
    details: {
      challenge: 'A legacy Blue Prism process and Excel macros limited speed and maintainability of SAP finance tasks.',
      approach: 'Rebuilt the process in UiPath with SAP and Excel automation, proper exception handling and Orchestrator-run integration.',
      flow: ['Legacy Bot', 'Assess', 'Rebuild', 'SAP Extract', 'Variance Report', 'Deliver'],
    },
  },
  {
    id: 'p05',
    index: '05',
    title: 'File Reception Control',
    category: 'Process Automation',
    icon: 'fileCheck',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    duration: '3 months',
    description: 'A robot that validates incoming batch files and flags errors before processing.',
    highlights: ['Automated batch-file validation', 'Error detection', 'Reduced manual error checking by 60%'],
    tags: ['RPA', 'Batch Files', 'Validation'],
    outcome: { value: 60, suffix: '%', label: 'less manual error checking' },
    details: {
      challenge: 'Batch files were checked for errors by hand before processing.',
      approach: 'An unattended robot reads each received file, runs error checks and reports issues for action.',
      flow: ['File Received', 'Parse', 'Validate', 'Detect Errors', 'Report'],
    },
  },
  {
    id: 'p06',
    index: '06',
    title: 'Pending Transaction Report',
    category: 'Data & Reporting',
    icon: 'table',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    duration: '2 months',
    description: 'Finds credit transactions awaiting approval across large, multi-department data and reports them automatically.',
    highlights: ['Automated pending-transaction identification', 'Approval tracking', 'Large-scale data processing', 'Automated reporting'],
    tags: ['RPA', 'Excel', 'Pivot Reports', 'Big Data Sets'],
    details: {
      challenge: 'Pending credit transactions needing approval were spread across millions of data points from multiple departments.',
      approach: 'Automation consolidates the data, identifies pending items and generates pivot reports for approvers.',
      flow: ['Collect Data', 'Filter Pending', 'Consolidate', 'Pivot Report', 'Distribute'],
    },
  },
  {
    id: 'p07',
    index: '07',
    title: 'Off Plan Phase 1',
    category: 'Document Automation',
    icon: 'fileScan',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    duration: '2 months',
    description: 'Supports customer housing-loan processing by extracting data from multilingual PDFs and invoices.',
    highlights: ['Customer housing loan automation', 'UiPath + ABBYY', 'Multilingual PDF data extraction'],
    tags: ['UiPath', 'ABBYY', 'OCR', 'PDF'],
    details: {
      challenge: 'Housing-loan approval depended on data inside multilingual PDFs and invoices.',
      approach: 'UiPath with ABBYY extraction reads the documents and feeds structured data into the loan process.',
      flow: ['Documents', 'OCR (ABBYY)', 'Extract', 'Validate', 'Loan Process'],
    },
  },
  {
    id: 'p08',
    index: '08',
    title: 'Construction Finance',
    category: 'Document Validation',
    icon: 'building',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    duration: '2 months',
    description: 'Validates loan applications against engineer-provided PDF inspection reports to support lending decisions.',
    highlights: ['Loan application validation', 'PDF inspection report processing', 'Automated validation'],
    tags: ['PDF Automation', 'Validation Rules', 'RPA'],
    details: {
      challenge: 'Loan applications had to be cross-checked against PDF inspection reports.',
      approach: 'Automation reads inspection reports, validates application details and surfaces exceptions for decision-makers.',
      flow: ['Application', 'Read PDF', 'Extract', 'Validate', 'Decision Support'],
    },
  },
  {
    id: 'p09',
    index: '09',
    title: 'ESTR Phase 1',
    category: 'Monitoring & Compliance',
    icon: 'radar',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    duration: '2 months',
    description: 'Detects suspicious transactions for local customers and raises automated alerts into an investigation workflow.',
    highlights: ['Suspicious transaction detection', 'Automated alerts', 'Business investigation workflow'],
    tags: ['Monitoring', 'Alerts', 'Workflow'],
    details: {
      challenge: 'Suspicious transactions needed to be detected and escalated quickly.',
      approach: 'Automation monitors transactions, applies detection rules and alerts investigators.',
      flow: ['Transactions', 'Monitor', 'Detect', 'Alert', 'Investigate'],
    },
  },
  {
    id: 'p10',
    index: '10',
    title: 'Fetch LG Process',
    category: 'Web Automation',
    icon: 'globe',
    domain: 'Banking',
    location: 'Onsite · Saudi Arabia',
    role: 'Developer',
    duration: '1 month',
    description: 'Web automation that integrates with an external application to extend policy bonds automatically.',
    highlights: ['Web automation', 'External application integration', 'Automated policy bond extension'],
    tags: ['Web Automation', 'Integration', 'Data Extraction'],
    details: {
      challenge: 'Policy bond extensions required manual work in an external application.',
      approach: 'A web automation robot connects to the external application, retrieves the required data and completes the extension process.',
      flow: ['Trigger', 'Open Application', 'Extract Data', 'Extend Bond', 'Update'],
    },
  },
  {
    id: 'p11',
    index: '11',
    title: 'Dealership Process Automation',
    category: 'Web & Desktop Automation',
    icon: 'app',
    domain: 'Automotive Retail',
    location: 'Offshore · India',
    role: 'Developer',
    teamSize: '6',
    description: 'Software robots for dealership business processes across sales, financing and after-sales operations.',
    highlights: [
      'Web and desktop application automation',
      'UiPath infrastructure set-up and deployment via Git & Orchestrator',
      'Business-rule file used as the team’s development input',
      'Requirements closed with SMEs and business analysts',
    ],
    tags: ['UiPath', 'Orchestrator', 'Git', 'Web & Desktop'],
    details: {
      challenge: 'Repetitive dealership operations were handled manually across web and desktop applications.',
      approach: 'Introduced software robots, set up the UiPath infrastructure and deployment pipeline, and drove development from a shared business-rule file.',
      flow: ['Request', 'Web Portal', 'Desktop App', 'Business Rules', 'Update', 'Notify'],
    },
  },
  {
    id: 'p12',
    index: '12',
    title: 'Hospitality Operations Automation',
    category: 'Web & Windows Automation',
    icon: 'workflow',
    domain: 'Hospitality',
    location: 'Offshore · India',
    role: 'UiPath Developer',
    teamSize: '10',
    description: 'UiPath automation of operational roles across web and Windows applications, with daily execution dashboards.',
    highlights: [
      'Web and Windows application automation',
      'PDD and SDD updates for change requests',
      'UAT → production moves and scheduled runs',
      'L2 monitoring, bug fixing and daily client dashboards',
    ],
    tags: ['UiPath', 'Web Apps', 'Windows Apps', 'Scheduling'],
    details: {
      challenge: 'Many operational roles involved repetitive work across web and Windows applications.',
      approach: 'Automated the processes in UiPath, moved them through UAT to production on schedules, and reported execution through daily dashboards.',
      flow: ['Schedule', 'Web App', 'Windows App', 'Process', 'Dashboard', 'Report'],
    },
  },
  {
    id: 'p13',
    index: '13',
    title: 'Accounts Payable & Reconciliation Analytics',
    category: 'Analytics Automation · Alteryx',
    icon: 'fileSheet',
    domain: 'Financial Services',
    location: 'Offshore · India',
    role: 'Alteryx Developer',
    teamSize: '5',
    description: 'Enhanced Alteryx workflows to automate accounts payable and financial reconciliation.',
    highlights: ['Accounts payable automation', 'Financial reconciliation', 'Defect tracking in Quality Center', 'Daily stakeholder status reporting'],
    tags: ['Alteryx', 'Reconciliation', 'Quality Center'],
    details: {
      challenge: 'Accounts payable and reconciliation relied on an existing analytics solution that needed enhancement.',
      approach: 'Extended the Alteryx workflows to automate matching and reconciliation, with defects tracked through Quality Center.',
      flow: ['Invoices', 'Alteryx Flow', 'Match', 'Reconcile', 'Exceptions', 'Report'],
    },
  },
]

export const certifications: Certification[] = [
  { id: 'uip-adp', name: 'Automation Developer Professional', provider: 'UiPath', issuer: 'UiPath Certified Professional', level: 'Professional', validUntil: 'December 2028', credentialId: '170458453', verifyUrl: 'https://credentials.uipath.com/9ae84059-b67e-4e89-8991-e0359e6fda7d' },
  { id: 'uip-agentic', name: 'Agentic Automation Associate', provider: 'UiPath', issuer: 'UiPath Certified Professional', level: 'Associate', validUntil: 'June 2029', credentialId: '184800237', verifyUrl: 'https://credentials.uipath.com/873e3109-7686-4915-b707-f759d327cc7b#acc.6z1bPvlc' },
  { id: 'aa-master', name: 'Master RPA Professional', provider: 'Automation Anywhere', issuer: 'Automation Anywhere Certified', level: 'Master', validUntil: null, credentialId: '57865218', verifyUrl: 'https://certificates.automationanywhere.com/d9d2e11a-dc43-41ed-9924-38d86a79e6a1' },
  { id: 'aa-advanced', name: 'Advanced RPA Professional', provider: 'Automation Anywhere', issuer: 'Automation Anywhere Certified', level: 'Advanced', validUntil: null, credentialId: '55032895', verifyUrl: 'https://certificates.automationanywhere.com/6f41ffd2-5d0b-4d5f-bcbe-486bff2bd224#acc.8iGc4Vx9' },
]

export const contact = {
  headline: "Let's Build Something Automated.",
  text: "Have an automation challenge or an idea worth automating? Let's connect.",
  email: 'sagar.das.knj.001@gmail.com',
  linkedin: 'https://www.linkedin.com/in/sagar-das-b182661a7/',
  instagram: 'https://www.instagram.com/i__am.sagar',
}
